README.md, src/index.ts, src/packExternalModules.ts
closes #23 - This approach makes more sense than #24.
=> feat: exclude option

src/pack-individually.ts
This PR excludes the other handlers' bundles directory (as opposed to bundler file before), thus ignoring also source maps in the individual packaging.
=> fix(package): exclude complete bundle directory

README.md, examples/individually/plugins.js, examples/individually/serverless.yml, src/index.ts
This is a naive implementation, but that might be all we need here.
I used the `plugins` key to let users pass on a path to the plugin definition file. Should it be named `pluginsDefinitionFile` or something in this taste? I think "plugins" is enough - but can be changed.
=> feat(esbuild): support esbuild plugins

README.md, package.json, src/index.ts, src/pack.ts, src/types.ts, src/utils.ts
- Update to latest @types/serverless which supports package.patterns
- Updated README to mention patterns and updated link to serverless docs
- Uses package.patterns instead of patterns.include in the global package section
- Added support for package.patterns on individual functions. It does this by copying the individual files into a special folder in the build folder, which gets ignored by all other functions. Then that special folder prefix gets removed when the intended function is packaged.
I'm not sure it's the best way to solve but at least it's a way to solve it :)
=> fix: #110 package.patterns

src/helper.ts, src/pack-externals.ts, src/pack.ts, src/packagers/yarn.ts
This excludes optional dependencies to be installed when resolving peer dependencies. 
It also replaces glob with globby in `pack.ts`, however, this does not change much anything as we still need to `stat` for the file mode. Globby can stat for us in one pass, but the types are not yet complete on their side. I took the lazy route here and just replaced glob. We can improve that later on.
=> fix(packaging): exclude optional peer dependencies

src/pre-local.ts
I debugged the problem #120 and found that the function [invokeLocalNodeJS](https://github.com/serverless/serverless/blob/6d2ed840fb21d469d8e4a548a38ca9302d5a9d2c/lib/plugins/aws/invokeLocal/index.js#L745) will use `this.serverless.serviceDir` to set the path to the transpiled handler entry file.
I also compared this with [serverless-webpack](https://github.com/serverless-heaven/serverless-webpack/blob/a2de4d8a93c448a45e501f846f9232d774589578/lib/prepareLocalInvoke.js#L20) and they handle this similar.
@floydspace can you check if I missed to set this correctly when `service.package.individually` is set to `true`.
=> fix(pack): servicePath not set for invoke local

src/index.ts
Currently, this plugin calls the ESBuild `build` method each time a file is changed.
As documented in #98, this behavior results in exponentially increasing memory usage as files are changed. Personally, I saw my memory usage (from the esbuild process) spike from an initial value of 600 MB to 2GB after just 5 changes. Ultimately, the memory usage results in a fatal error, where the JavaScript heap runs out of memory. 
In this pull request, I've added a conditional check in the `bundle` method to call `rebuild` instead of `build` if there are existing build results.
I also set the `bundle` method to enable incremental builds by default. From what I understand, the way the ESBuild process works is as documented [here](https://esbuild.github.io/api/#incremental):
1. Create an initial build …
=> Check for existing results to rebuild

src/helper.ts, src/index.ts, src/pack.ts
individually option usage together with custom function name could lead to file name issues
fix #128
=> fix(sls): fix function artifact name in case of individually option usage

README.md
Currently if you click the `See example folder for a minimal example.` link in the README.md it takes you to https://github.com/floydspace/serverless-esbuild/blob/master/example (singular), which is not a valid url.
Instead it should take you to https://github.com/floydspace/serverless-esbuild/blob/master/examples (plural)
=> Fix bad example link in README.md

src/index.ts
Currently the plugin accesses `this.serverless.service.custom?.esbuild` within the constructor. This does not work when imported variables are used, e.g. `${file(...`
```yml
esbuild:
packager: npm
bundle: true
define: ${file(./serverless.js):define}
```
The `${file...} import is not resolved in the constructor but only when called after the constructor call.
=> fix(sls file imports): Use generate config outside of the constructor

src/index.ts, src/pack.ts, src/utils.ts
Hello and thanks for this awesome plugin !
When debugging a performance issue on some of my lambdas, I found that it was not possible to output the meta files and therefore the debugging was a bit painful.
This is due to a specific implementation of the esbuild metafile option, that returns the meta in the result object of the build, but delegates the handling of it to its caller : https://esbuild.github.io/api/#metafile
Closes: https://github.com/floydspace/serverless-esbuild/issues/121
=> feat: write metafile when the metafile option is set to true

src/pack.ts
This is a fix.
When functions have names with prefix which is same as any other function name, their bundled js files are being excluded in the final artefact.
Ex: For an application having two functions with names `function-name` and `function-name-other`. The packaging (individually) is excluding the bundled `js` & `js.map` files for `function-name-other` in the final artefact.
=> fix(pack): function files with names whose prefix is same as other function names

src/index.ts
Copying over [this flag](https://github.com/serverless-heaven/serverless-webpack#keep-output-directory-after-packaging) from the serverless-webpack plugin. Can be very useful in diagnosing not only build issues but in tandem with the `metafile` option for analyzing bundle size.
=> feat: keepOutputDirectory flag

src/index.ts
Esbuild needs plugins config to load the plugins. Since `plugins` is an expected BuildOption, I think it is safe to retain it.
``` ts
export interface BuildOptions extends CommonOptions {
bundle?: boolean;
splitting?: boolean;
preserveSymlinks?: boolean;
outfile?: string;
metafile?: boolean;
outdir?: string;
outbase?: string;
platform?: Platform;
external?: string[];
loader?: { [ext: string]: Loader };
resolveExtensions?: string[];
mainFields?: string[];
conditions?: string[];
write?: boolean;
allowOverwrite?: boolean;
tsconfig?: string;
outExtension?: { [ext: string]: string };
publicPath?: string;
entryNames?: string;
chunkNames?: string;
assetNames?: string;
inject?: string[];
banner?: { [type: string]: string };
footer?: { [type: string]: string };
incremental?: boolean;
entryPoints?: …
```
=> fix(esbuild): include plugins config for esbuild

README.md, src/index.ts, src/pack-externals.ts
This gives the ability to run custom scripts after packager install.
Use cases: remove/clean-up node modules etc.,
I have tested this with both `yarn/npm`, also w/ packaging individually `true/false`
You can find the reference script here: 
https://github.com/vamche/sls-esbuild-node-externals/blob/7a88127993acda4b12867245e8ac023cc68a6e13/serverless.yml#L22-L25
=> feat(packager): ability to run custom scripts after packager install

src/pack-externals.ts, src/tests/util.test.ts, src/utils.ts
A problem arouse in one of my project : mongoose was required by a dependency with a specific version. We put mongoose as external because it relies on system code.
But as mongoose was not listed as dependency of our project, its version was not caught by the plugin ; as such a later, incompatible version of mongoose was packaged.
This PR changes the way we get the dep versions by checking the module package.json found either in node_modules or the root node_modules (in case of a workspaced project).
It also changes the arguments to get the project root (a package.json is always found even if it is not the root).
=> fix(package): fix wrong argument to get package's root

README.md, package.json, src/index.ts, src/pack.ts, src/utils.ts
bestzip preserves file timestamps, which causes function zips to be different after every esbuild.
Because there are scenarios where native js zipping is unacceptably slower than native system zip, the option to use it is preserved as an option.
Fixes: #186
=> feat(zip): make bestzip an off-by-default option

src/pack-externals.ts
I had a bug today where yarn would try to install my externals with --frozen-lockfile, even from a service in a monorepo. Checked the code, and actually, we were resolving the lockfile from the root package json path - whereas the original PR for this feature stipulates that the lockfile should be sought at the local level - thus determining if we should use frozen lockfile or not.
This will not affect users out of a monorepo.
I am fixing this now, But I really think we should take some time to review the all packaging step, as it has become quite complex PR after PR. But time is hard to find :-).
=> fix(pack): local lockfile resolved at wrong location

src/pack-externals.ts
Resolves #196
If you have a package listed in `external` which is *not* in the package.json dependencies, the plugin will try and install it anyway.
The documentation states the following:
```
Packages that are marked as external and exist in the package.json's dependencies will be installed and included with your build under node_modules.
```
- aligns the behaviour of `external` with the documentation.
=> feat: ignore external module if not declared in package.json

README.md, package.json, src/index.ts
For some use cases, where there is limited system memory available (i.e. GitHub Actions 7GB), esbuild can run out of memory and crash when building a big serverless project (i.e. 50+ lambdas).
In order to overcome that I've added the esbuild option _concurrency_ to only allow as much as _concurrency_ promises running at the same time when building the lambdas.
I could help with the tests, and indeed I tried to work on them, but there is a lot to reestructure in the index.ts before unit tests start to make sense.
Closes #200
- Run _serverless package_ command with the esbuild option _concurrency_ as an integer
- It should limit the concurrent building of the service lambda's to that amount
- Run _serverless package_ command with the esbuild option _concurrency_ as a string
- It should …
=> feat: set up concurrency on building the lambdas

README.md
In some situations it can be useful to include only some dependencies as external but allowing other dependencies to be bundled, one such example is when creating AWS Edge lambdas which have limit on deployment package sizes.
This commit adds to the docs an example of how to do this which isn't otherwise immediately obviously without going to look at example serverless.yml files.
=> Add docs for how to mark individual packages as external

src/index.ts
**Motivation: preventing a memory leak**
When used in combination with serverless-offline on a typescript codebase of about 200.000 lines of code, my colleagues and I have observed a memory leak that caused in our case about 500Mb to be consumed on each code change triggering a recompilation (as described in  #98). After some experiments with serverless-esbuild's code, it turned out that totally disabling incremental compilation made the problem disappear. Since esbuild is extremely fast, giving up incremental compilation did not affect our development speed, which is why we want to propose to add an option to do that.
=> feat: added disableIncremental option to completely turn off incremental compilation

src/index.ts
This PR is a follow up to #231 since, when disabling incremental compilation, the `BuildResult` object does not have the rebuild property:
```
export interface BuildResult {
...
/** Only when "incremental: true" */
rebuild?: BuildInvalidate;
...
}
```
which makes `await result.rebuild();` throw an error that turns into a bundling error that prevents hot reload from working.
=> fix: don't invoke result.rebuild when it is not defined

src/helper.ts, src/tests/helper.test.ts
Resolves #235
Resolves #234
This allows for users to set the function handler using the relative path operator: eg.
```
func1:
handler: ./file1.handler
```
=> fix: allow relative path for function handler

src/helper.ts, src/tests/helper.test.ts
Fixes #243
On Windows `path.relative` adds `\` to paths instead of `/` and esbuild does not like this when we pass it in as an entrypoint.
Replace all `\` with `/` in paths for Windows.
Unit Tests
=> fix: correct package individually relative path for Windows

package-lock.json, package.json, src/packagers/npm.ts, src/tests/packagers/npm.test.ts
Fixes: https://github.com/floydspace/serverless-esbuild/issues/144
Module dependencies are missing for the externals for npm v7+
=> fix(npm): updated getProdDependencies to support npm v7+

src/index.ts
If you ask serverless to package your functions individually, the plugin will try to package everything, causing a crash if you have functions that were already filtered out by the code in `get functions()`.
(You can work around this by adding a dummy "- package: { artifact: '' }` property of the function.)
This just changes what functions need to be packaged to the ones that are valid.
=> fix: do not set package artefact for non-node functions

README.md, src/index.ts
Resolves #258
To enable ESM support simply override the `platform` option in the esbuild plugin settings. View the esbuild [documentation](https://esbuild.github.io/api/#platform) for more information. The `platform` key defaults to `node`. 
eg.
```yml
custom:
esbuild:
platform: neutral
```
- Allow `platform` to be overwritten in the options.
=> feat: enable esm support

src/helper.ts, src/packagers/npm.ts, src/packagers/packager.ts, src/packagers/yarn.ts, src/tests/helper.test.ts, src/tests/packagers/npm.test.ts, src/tests/packagers/yarn.test.ts, src/types.ts, src/utils.ts
Resolves #265
Resolves #103
Resolves #135
- The current `yarn` dependency resolution logic does not take into consideration the version of the package it is looking for. This meant that if there was another version of a package of the same name with different dependencies we may not bring the correct dependencies into the package. This could cause extra or less packages to be included in the package.
- The current `npm` dependency resolution logic does not consider when a package is de-duped by another package. This leads to issues when multiple dependencies share the same version dependency.
- Unify output of the dependency tree shape and behavior of `npm` and `yarn` packagers. This should hopefully lead to more consistency.
- Update `flatdep` logic
=> fix(external): update npm and yarn dependency detection

src/helper.ts, src/index.ts, src/pack-externals.ts, src/pack.ts, src/pre-local.ts, src/pre-offline.ts, src/tests/helper.test.ts, src/tests/index.test.ts, src/tests/pack.test.ts, src/tests/packagers/npm.test.ts, src/tests/util.test.ts, src/types.ts, src/utils.ts, tsconfig.json
While working on https://github.com/floydspace/serverless-esbuild/pull/261 I tried to write some unit tests involving the `EsbuildServerlessPlugin` class but I could not import it without Typescript complaining in Jest. I tried both `import EsbuildServerlessPlugin * from './index"` and `import {EsbuildServerlessPlugin} * from './index"`
Happy to go with another approach if you can tell me something else which works 🤷 .
In order to overcome this in the test I had to convert the `module.exports = EsbuildServerlessPlugin` to `exports = EsbuildServerlessPlugin`. This complained about other things being exported in the file so I moved all the type definitions to `types.ts`. This still produces the desired `module.exports = EsbuildServerlessPlugin` in the output `index.js`.
This approach seems …
=> fix: use esModuleInterop and remove tests from package

.github/workflows/pull.yml, .github/workflows/release.yml, README.md, package-lock.json, package.json, src/helper.ts, src/index.ts, tsconfig.json
Drop Node 10 support. AWS no longer supports Node 10.
Good timing as I could not get packaging to work for npm using Node 10. It would always fail with this mysterious error.
```
fs.js:114
throw err;
^
Error: ENOTEMPTY: directory not empty, rmdir '/var/folders/ny/t5slkz216xxdqzxcy049sm0r0000gq/T/hello1-1644476876876'
at Object.rmdirSync (fs.js:684:3)
at WriteStream.output.on (/Users/schung/me/serverless-esbuild/dist/utils.js:142:20)
at WriteStream.emit (events.js:198:13)
at WriteStream.EventEmitter.emit (domain.js:448:20)
at lazyFs.close (internal/fs/streams.js:207:14)
at /Users/schung/me/serverless-esbuild/examples/individually/node_modules/graceful-fs/graceful-fs.js:61:14
at FSReqWrap.args [as oncomplete] (fs.js:140:20)
```
- Switch compile target to es2019 for optimised bundle. es6 …
=> feat: drop support for Node 10

.github/workflows/release.yml
Ruh roh, this version of semantic release requires node 14 to run 😆 . Feel free to merge whenever.
=> ci: bump up node version for release

package-lock.json, package.json, src/helper.ts, src/index.ts, src/pack-externals.ts, src/pack.ts, src/packagers/index.ts, src/tests/index.test.ts, src/tests/pack.test.ts
Hello!
I have implemented a small logging interface that makes use of the new logging capabilities of Serverless V3, but is still compatible with the legacy logger. I have tested with a project in V2 and another one in V3.
Cheers!
Fix: https://github.com/floydspace/serverless-esbuild/issues/259
=> Feat: Serverless v3 logs

package-lock.json, package.json, src/index.ts, src/tests/index.test.ts, src/types.ts
Hello ! Following https://github.com/floydspace/serverless-esbuild/pull/282, I added the `verbose` options to `@types/serverless`, so it is no longer necessary to extend its definition.
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58992
Cheers!
=> chore: use serverless v3 option types

src/helper.ts, src/pack-externals.ts
Semantic Release is case sensitive. Trigger release for #282.
Minor Change:
- Previously we had two distinguishable log types, verbose and regular which I think was useful for users eg. bundle size so I think users will likely want to use the --verbose flag in v3 but that would also bring in logs which may be less useful to them.
- Since in v3 they are the same, I've made the v2 verbose logs into debug logs so users can keep their logs similar to before.
=> feat: serverless v3 logs (#282)

src/packagers/npm.ts, src/tests/packagers/npm.test.ts
fixes https://github.com/floydspace/serverless-esbuild/issues/288
cribbed from https://github.com/serverless-heaven/serverless-webpack/pull/782
simplified ignored error checking (removed ramda reduce in favour of ES5+ native `Array.every()`
=> fix: ignore npm v7+ err ELSPROBLEMS

src/helper.ts, src/tests/helper.test.ts
Tweak the `flatDep` logic to add the dependency to the found list before finding other dependencies. This should prevent any circular dependency issues arising in the future.
https://github.com/floydspace/serverless-esbuild/issues/205#issuecomment-1089264328
=> fix: prevent circular dependency loop in flatDep

.github/workflows/pull.yml, .github/workflows/release.yml, README.md, src/helper.ts
Hi! nodejs16.x lambda runtime was just released, this adds support for using it together with serverless-esbuild
=> feat: add nodejs16.x runtime support

package-lock.json, package.json, src/utils.ts
This pull request updates the `fs-extra` dependency and uses the `removeSync` method to avoid the following warning on Node.js v16+:
`[DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead`
=> Fix `fs.rmdir` deprecation warning

src/packagers/npm.ts, src/tests/packagers/npm.test.ts
Resolves #286
I think we should consider enabling `"strictNullChecks": true` which I'm used to having on most of my repos. But I may try this in a different PR as I think there might be a few other code smells around the place.
=> fix: handle empty or missing npm dependency tree

README.md, examples/config/config.js, examples/config/hello1.ts, examples/config/hello2.ts, examples/config/package-lock.json, examples/config/package.json, examples/config/serverless.yml, src/index.ts, src/types.ts
Hey guys. 
This PR adds support to specify a config file. So the user can have more control about the configuration. 
For example: If I want to define all my dependencies as external I have to use a esbuild plugin or define in the serverless.yml the entire list of dependencies.
Using a config file lets the user to solve this by:
```js
module.exports = () => ({
external: Object.keys(require('./package.json').dependencies)
})
```
Without having to install new dependencies or esbuild plugins that can impact in the performance.
=> feat: add support for config file

src/pack-externals.ts
Hey.
This PR ensures that a provided `packagePath` is always resolved relative to the current working directory e.g serverless.yml dir.
Currently the `packagePath` is resolved based on the directory containing the currently executing file, i.e `/my-project/node_modules/serverless-esbuild/dist/pack-externals.js`;
https://github.com/floydspace/serverless-esbuild/blob/2c1d2ac842ac4270c48028d123887193ae957af2/src/pack-externals.ts#L78
If you change the `packagePath` with this in mind then it fails over when trying to resolve the `package-lock.json` later due to trying to resolve relative to the current working directory.
https://github.com/floydspace/serverless-esbuild/blob/2c1d2ac842ac4270c48028d123887193ae957af2/src/pack-externals.ts#L311
- I have used `process.cwd()` to determine current …
=> fix: packagePath correctly treated as relative path from service dir

README.md, src/bundle.ts, src/helper.ts, src/pack.ts, src/tests/bundle.test.ts, src/tests/helper.test.ts
Recommend setting `format` to `esm` to enable ESM support. This PR enables us to recognise when we are in "ESM" mode or not.
Leaving the platform as `node` has its advantages.
eg. 
```
All [built-in node modules](https://nodejs.org/docs/latest/api/) such as fs are automatically marked as [external](https://esbuild.github.io/api/#external) so they don't cause errors when the bundler tries to bundle them.
```
=> fix: enable `esm` format

src/index.ts, src/tests/index.test.ts
Absolute artifact paths break deployment in scenario where serverless package runs in one folder
and later serverless deploy runs in a different folder (happens in CI/CD systems).
Serverless Framework uses the artifact path to determine the location of the file to copy from.
Closes #324
=> fix: use relative path for artifact file

package-lock.json, package.json, src/helper.ts, src/tests/helper.test.ts
I noticed `getDepsFromBundle()` was not finding dynamic imports using `import()`.
I've updated the code to use `acorn` and `acorn-walk` to find dependencies imported using `import 'XXX'`, `import('XXX')`, and `require('XXX')`.
=> refactor: `getDepsFromBundle` now walks an AST

src/index.ts, src/tests/index.test.ts
closes #334
Hey,
This PR ensures that the buildOptions is set in the initialize hook. 
https://www.serverless.com/framework/docs/guides/plugins/creating-plugins#lifecycle-events
As per their docs the previous method meant that the serverless object passed to `config()` had variables that were not resolved...
> Note: configuration values are only resolved after plugins are initialized. Do not try to read configuration in the plugin constructor, as variables aren't resolved yet. Read configuration in lifecycle events only.
- I have removed the dependency on `memoizeWith` as now the buildOptions is only set once.  As the class field has not changed name or the returning value, no changes are required in any other file.
=> fix: set buildOptions in new initialize function

package-lock.json, package.json
Resolves #360 
Might need to do some changes to support yarn pnp and pnpm but otherwise we should let consumers keep up to date.
=> fix: allow esbuild versions < 0.16

src/pack-externals.ts, src/pack.ts, src/packagers/index.ts, src/tests/packagers/index.test.ts, src/tests/type-predicate.test.ts, src/type-predicate.ts, src/types.ts
Rewrote instantiating a `Packager` to be asynchronous.
- correctly call it so that `this` is the correct plugin
- Packager instance is memoized
=> refactor: asynchronously create packager instance

src/bundle.ts, src/pack-externals.ts, src/types.ts
Add configuration option `nodeExternals` which allows to pass `allowList` array for the `esbuild-node-externals` plugin.
This intends to solve https://github.com/floydspace/serverless-esbuild/issues/250
=> feat: add nodeExternals configuration for esbuild-node-external plugin

src/helper.ts
My organization uses .jsx/.tsx serverless handlers to generate and send emails using react-dom/server renderToStaticMarkup. However, serverless-esbuild cannot find our handlers, because it is only checking for `.js` and `.ts` files.
=> feat: allows .jsx and .tsx as valid handler extensions

README.md, src/helper.ts
🎉  https://aws.amazon.com/blogs/compute/node-js-18-x-runtime-now-available-in-aws-lambda/
=> fix: node18 support

package-lock.json, package.json, src/pack-externals.ts
- Added `esbuild-node-externals` as a dev dependency and optional peer dependency
- This allows us to use the types from their package during development.
- Refactored how `esbuild-node-externals/dist/utils` was being detected.
- `require.resolve()` is now used instead of a hard coded relative path.
=> refactor: node externals

src/helper.ts, src/tests/helper.test.ts
Adds code (and a test) that searches for the handler file as an `index.[js|ts|tsx|jsx]`. This way one can point to a directory with an index file that exports the handler function, instead of requiring the author to name the exact file that exports the handler.
Directory structure:
```
- handlers
- foo
- index.ts
```
`serverless.yml`:
```
functions:
foo:
handler: handlers/foo.foo
```
=> feat: add support for dir/index handlers

src/index.ts
fixes #415
@webdeveric there was a `patterns` array that was shadowed and led to stack overflow apparently.
=> fix: get rid of harmful shadow variable

README.md, src/index.ts, src/tests/index.test.ts, src/types.ts
I've got multiple projects where I'm using serverless-esbuild and it's working great. But I'm building my own custom plugin for these projects where I'm adding a function and defining my own artifact zip file. Turns out though, serverless-esbuild will try to run esbuild even if an artifact is already defined. I'm sure this use case wasn't something that was thought of in the beginning, but I feel like it's something this should account for. 
This has also been brought up in #376
I tried going a variety of different routes, but the best solution I have so far is to make it so you can set a property when you define the function called `skipEsbuild` and if it's `true`, then it'll just skip over it. I'm leveraging the [Serverless schema configuration …
=> feat: add skipEsbuild option on a per function level

src/helper.ts
Hello,
The current implementation of NodeMatcher fails when using with Google Cloud because Google expects a different format for the runtime.
Aws expects a format like `nodejs${Version}.x`
Google expects a format like `nodejs${Version}`
This PR allows the use of both format depending of the provider.
=> fix: node matcher for google

src/pack.ts
My last PR (#428) had a small boolean logic error, by grabbing all the exclude patterns and then simply running globby on them, we were effectively gathering nothing, rendering the change ineffectual.  In order to properly gather the list of files to exclude, we need to remove the `!` from the exclusion patterns so we can actually get the results we want from globby.
=> fix: remove ! from exclusion pattern list for proper matching

package-lock.json, package.json, src/bundle.ts, src/tests/bundle.test.ts, src/types.ts
Adds support for Esbuild's breaking API changes introduced in 0.17 without removing support for earlier incremental rebuilds. 
Addresses issue #427,
=> Feature: Add support for both old and new ESBuild Incremental APIs

README.md, src/index.ts, src/types.ts
This adds support for overriding chokidar options by setting them under the watch section of the options. This is useful because the appropriate value for `awaitWriteFinish` is dependent on the OS and hardware.
I also removed setting `awaitWriteFinish` by default as I don't think it's a good idea as I explain in the commit message. Though, if you disagree with this, I'd rather get the rest of the PR merged without that than nothing at all, so I at least can unset it myself.
I also changed the options to be deeply merged, because otherwise you have to set all the default values under a section if you set a value in it. E.g. if you set anything under watch, you had to specify patterns as well, otherwise nothing is watched. With a deep merge, only the specific options you set are overridden. …
=> Allow overriding chokidar options

README.md, e2e/__snapshots__/complete.test.ts.snap, e2e/__snapshots__/individually.test.ts.snap, e2e/__snapshots__/minimal.test.ts.snap, src/helper.ts, src/tests/helper.test.ts
Adds support for Azure Function Apps built in Node via the `serverless-azure-functions` plugin.
Currently when trying to use the plugin with the `azure` runtime it does not compile because there is not a function matcher available, only for AWS and GCP.
This commit adds a matcher for Azure, along with unit tests and supporting documentation in README.md.
I originally had #445 opened, but upon further investigation the `esbuild` binary was never being invoked because the plugin ignored all `azure` runtime functions. I have since created a matcher and can confirm that the `esbuild` plugins functionality is working correctly.
This PR is raised to increase the compatibility of the plugin with other serverless runtimes, but it might be pertinent to add a warning whenever a function is being …
=> feat: adds support for `serverless-azure-functions` plugin

src/bundle.ts, src/helper.ts, src/tests/helper.test.ts
There were three warnings from eslint, two about console.log and one about BuildResult only used as a type.
=> fix: lint warnings

README.md, src/index.ts, src/packagers/yarn.ts, src/types.ts
As a result of my issue filed in #435, we can detect the version of Yarn being used by the user and set the appropriate packager args.
* `--non-interactive` was removed from Yarn 2+
* `--frozen-lockfile` was changed to `--immutable` in Yarn 2+
* However, because of the new nature of Yarn `--immutable`, if you are using `external` dependencies the lockfile will always fail because we generate a new package.json with only the externalized dependencies. Therefore, I added `ignoreLockfile` as a Yarn only packagerOption to bypass this.
Closes #435 #433
=> fix: external incompatibility with Yarn 2+; conditionally set packager args

src/bundle.ts
Previously the build results were stored in a cache, but the context was immediately disposed. This caused an error because the context object was still in the cache, so when rebuilding it tried to call .rebuild() on the context on line 97 which threw an exception because you can't call rebuild on disposed contexts.
I don't get why contexts are stored in a cache and tried rebuilding on if they are disposed, so I removed disposing them all together. If they should still be disposed, the context needs to be completely removed, so it doesn't try calling rebuild on it.
Fixes #439
=> fix: don't dispose build contexts

.all-contributorsrc, src/helper.ts, src/pack.ts
Added support for Scaleway nodetypes and provider. 
fixes #458
=> Add scaleway nodeversion support

src/helper.ts
When moving from a different bundler to serverless-esbuild it can be hard to find mistakes with the generic error message provided in the `extractFunctionEntries` method.
To give developers at least a hint where the issue can be found this change adds the function alias to the error message.
=> feat: improves error message when handler is not found

src/index.ts
This is my first time contributing. Please let me know what you'd like to see in terms of tests, documentation, etc - thanks!
- With a default `serverless-offline` + `serverless-esbuild` setup, watching for changes does not work
- See https://github.com/floydspace/serverless-esbuild/issues/108
- The `--reloadHandler` solution proposed in the above issue drastically hurts local dev performance on a large project
- Leverage https://github.com/dherault/serverless-offline/pull/1093 to tell `serverless-offline` when it needs to clear the cache
- If https://github.com/floydspace/serverless-esbuild/issues/158 was built, this may not be necessary
- For example with `serverless-webpack`, which already supports lifecycle hooks, I use a custom plugin to solve this exact same problem:
```js
class …
```
=> Notify serverless-offline when watched files trigger rebuild

src/bundle.ts, src/index.ts
My initial upgrade to esbuild 0.19 causes an easily reproducible issue that made the plugin spawn too many esbuild builds that would cauase memory to spike. This can be seen if you set esbuild to watch for changes and then repeatedly save the same file over and over.
I caused these as I ran into an issue where running serverless invoke and serverless package would never finish when calling rebuild. Using build seemingly solved this, but it ended up causing the issue spawning too many builds described above.
The actual underlying issue was that the context of these rebuilds are needed to be disposed of when we are finished building.
I added a step on finishing invoking, deploying and packaging to make sure to dispose of the contexts. I did not dispose of them on long running process of …
=> Fix spawning too many esbuilds builds

src/index.ts
Hey guys, 
I was trying to update serverless-esbuild to the latest version but I was having issues invoking local functions with `serverless invoke local -f <function>` and using the custom config esbuild file feature.
```yaml
custom:
esbuild:
config: esbuild.config.js
```
I was getting this error:
```
Error: Cannot find module '<project-path>/.esbuild/.build/esbuild.config.js'
```
And the thing is that only for the pre-local script monkey patching the serviceDir to the build project dir and for that change the `require` cannot find the esbuild.config.js
I made a simple change, cache the buildOptions.
By doing this we avoid to call the `getBuildOptions` twice and with the wrong configuration paths.
=> fix: custom esbuild.config.js loader

src/utils.ts
This is a quick fix for issue #485.
I stumbled upon it by accident but basically I had a yarn.lock file in my home folder, and because the mechanism for recursively finding the lock file of the project runs up the directory chain outside of the scope of the repo, it could happen.
In the issue i described 2 possible solutions i could see, and decided to push this parallel search as an easy way to fix it. It should basically look recursively up the folder tree for either a package-lock, yarn-lock or pnpm-lock file and stop when it finds one of them rather than first looking for a yarn.lock up into infinity and if it can't find one, move on to the next possible packer lock file and so forth...
=> fix: recursively search for packer lock file for all 3 packers supported

src/helper.ts
This is a minor change to enable support for nodejs20.x now that [Lambda supports it]( https://aws.amazon.com/blogs/compute/node-js-20-x-runtime-now-available-in-aws-lambda/)
=> Add support for nodejs.20x for Lambda

README.md, src/bundle.ts, src/constants.ts, src/helper.ts, src/index.ts, src/pack.ts, src/tests/helper.test.ts, src/types.ts
Support the ability to add custom resolution extensions via ESbuild settings. This is a feature of ESbuild and will allow for customization of lambda entrypoints. My team will be using this to support building different files based on the target environment we are deploying to.
Example:
`myLambda.dev.ts`
`myLambda.prod.ts`
`myLambda.ts`
When the environment we build for matches the extension of the file then that entrypoint will be used otherwise it will fallback to the default file resolutions in the order of our choosing. If the user of this plugin doesn't pass a `resolveExtensions` ESbuild setting then it will fallback to the array that was already defined by the repo.
https://esbuild.github.io/api/#resolve-extensions
When using custom extensions as the entrypoint for lambdas AWS can …
=> feat: add support for resolve extensions esbuild setting

README.md
This [code](https://github.com/floydspace/serverless-esbuild/blob/31dd88fe89d934a1178b3e50f1e390e5ccf2e4fb/src/helper.ts#L254) seams to support nodejs20.x but it is not included in the README.
I also noticed that [this plugins page on serverless.com](https://www.serverless.com/plugins/serverless-esbuild#supported-runtimes) is outdated but i don't know how to update that
=> Update README.md to include aws runtime nodejs20.x

README.md, src/bundle.ts, src/index.ts, src/types.ts
**Description:**
This pull request addresses the issue explained in [#514](https://github.com/floydspace/serverless-esbuild/issues/514). We identified a challenge regarding the handling of context disposal in the serverless-esbuild plugin, which caused error and changed behavior of Lambda functions on every 3rd local invoke.
**Changes Made:**
**New _'disposeContext'_ Property:** I introduced a new property named **disposeContext** which has a default value as **'true'** in both **Configuration** and **EsbuildFunctionDefinitionHandler** interfaces. This property allows users to control whether the _disposeContexts()_ function should dispose of the context.
**Configuration Flexibility:** The **disposeContext** option can be set globally within the esbuild configuration in the serverless …
=> Implement 'disposeContext' option in Configuration and EsbuildFunctionDefinitionHandler

README.md, src/helper.ts
This is a minor change to enable support for nodejs20 now that [Google Cloud Functions](https://cloud.google.com/functions/docs/concepts/nodejs-runtime) support it
=> Add support for nodejs20 for Google

src/bundle.ts
Really simple fix to the latest skipRebuild options.
It was missing before and threw an error if I tried to include the option in my esbuild config. Works fine now after adding it here
=> Fix: Added skipRebuild options to esbuildOptions

src/packagers/index.ts, src/tests/packagers/npm.test.ts
=> chore: fixed spelling issues

src/tests/util.test.ts, src/utils.ts
This means it's possible for code to retrieve the correct mtime, for example to return in a `Last-Modified` header. That's what I want to use this for: I'm bundling static assets in my Lambda and I want to be able to have clients cache them properly and send me `If-Modified-Since`.
Since we have a test which verifies a checksum of a zip file created by this function, we can be sure the results are deterministic. To support this, update the test inputs to have specified mtimes.
[Here's a test run on my fork][test]. You can see that I had to drop node 14 from CI, so if a run is approved it'll fail. This seems to be a pre-existing failure on master which [you can observe in other PRs][existing-failure].
[existing-failure]: https://github.com/floydspace/serverless-esbuild/actions/runs/91530019 …
=> fix: preserve mtime when zipping with the node zipper

src/tests/util.test.ts, src/utils.ts
This PR reverts commit 162d9bc7f0e87d63cd93adb0f4756d01769da79d, which introduced non-deterministic behavior in the bundling process, leading to unnecessary re-deployments even when no code changes occurred. This change addresses issue [#557](https://github.com/floydspace/serverless-esbuild/issues/557).
=> Revert "fix: preserve mtime when zipping with the node zipper (#539)"

src/bundle.ts
This PR addresses https://github.com/floydspace/serverless-esbuild/issues/388
It is inspired by https://github.com/floydspace/serverless-esbuild/issues/388#issuecomment-1773183932
I run several different services locally in parallel with serverless-offline and serverless-esbuild. The largest one of those was chewing up 30+ GB of RAM just to build and run locally, and it didn't come down after the build was done.  We kept having to bump our GitHub Actions to larger runners in order to be able to run our integration tests chiefly because of this memory leak.
We have been using this fork for a month; The memory usage is far less and there are no apparent issues. By using the fork, we've cut our GitHub Action spend in half.
=> Fix memory leak when skipRebuild is true

src/helper.ts
Node 22 runtime (current LTS) was recently added for Lambda:
https://aws.amazon.com/blogs/compute/node-js-22-runtime-now-available-in-aws-lambda/
=> feat: add node 22 support for AWS

.github/workflows/pull.yml, .github/workflows/release.yml, package-lock.json, package.json, src/tests/index.test.ts, src/types.ts
The 0.25.0 version of `esbuild` was [released a couple of weeks ago](https://github.com/evanw/esbuild/releases/tag/v0.25.0) - it fixes various issues, but also restricts access to the esbuild dev server to fix a security vulnerability.
This change updates the peer dependency compatibility range and also the dev dependency version so that users of `serverless-esbuild` can upgrade to `esbuild` 0.25.0 without getting peer dependency warnings from their package manager.
=> chore: update esbuild compatibility to include 0.25

src/index.ts, src/types.ts
This adds support for the `plugins` config file to be written in ESM format.
Example usage:
```js
// plugins.js
import MyPlugin from "my-esbuild-plugin";
export default [
MyPlugin()
];
```
=> feat: support ESM plugins

.github/workflows/pull.yml, .github/workflows/release.yml, src/helper.ts
Add support for Node 22 on Scaleway
Scaleway's supported list of NodeJS runtimes is available [here](https://www.scaleway.com/en/docs/serverless-functions/reference-content/functions-runtimes/#nodejs).
=> feat: add node22 support for scaleway

README.md
Thank you for maintaining this project!
This PR updates the README to include Node.js 22 in the list of supported AWS Lambda runtimes.
Node.js 22 support was added in [#560](https://github.com/floydspace/serverless-esbuild/pull/560), but the documentation was not updated accordingly. This change ensures that the README stays consistent with the actual runtime support.
Let me know if any additional changes are needed!
fix: https://github.com/floydspace/serverless-esbuild/issues/561
=> docs: add Node.js 22 to AWS Lambda supported runtimes
