- .prettierrc
- README.md
- examples/complete/package.json
- examples/complete/serverless.yml
- examples/complete/src/index.ts
- examples/minimal/index.js
- examples/minimal/package.json
- package.json
- src/helper.ts
- src/index.ts
1. Add the ability to watch files and auto-compile while using with serverless offline.
2. Update document with usage. 
Closes #84
> feat(watch): add ability to watch and auto-compile while using with serverless offline

- src/pack.ts
#92 helped keep from including extra map files, but it still includes too much. 
Storing `dirname` erases too much information and we cant distinguish siblings. So given:
```
/folder1/
/folder1/foo.ts
/folder1/bar.ts
[...]
/folder2/
/folder2/bat.ts
[...]
```
foo.zip gets both foo and bar (and their maps), and so does bar.zip, and so on.
This change assumes that there may be generated files that are not listed in `buildResults`, but that they are "prefix-named", that is `foo.js` => `foo.js.map` - generalizing, we ignore here `foo.js*`
> fix: don't include siblings in folder when packaging individually

- src/helper.ts
- src/pack.ts
This PR is a step towards fixing the google provider when packaging globally and fixes #105. Individual packaging is not provided yet.
> fix(package): fix google provider

- examples/individually/package.json
- examples/individually/yarn.lock
- src/index.ts
- src/pack.ts
- src/pre-local.ts
- src/pre-offline.ts
this should fix and close https://github.com/floydspace/serverless-esbuild/issues/117
> fix(serverless): allow use of newer serviceDir serverless key

- README.md
> chore: fix typo in the readme

- README.md
- src/pack-externals.ts
Closes https://github.com/floydspace/serverless-esbuild/issues/136
> feat(external): pack node_modules when esbuild-node-externals is configured

- package.json
- src/pack.ts
- src/utils.ts
> feat(zip): utilize bestzip instead of archiver

- README.md
I noticed `exclude` was mentioned briefly but kind of glossed over, then I realized it would be nice if the README just listed out the possible options for this plugin (not esbuild).
> Spelled out options specific to this plugin (not esbuild)

- src/pack.ts
- src/utils.ts
This should fix #150. It creates a temporary directory where every files is copied before being zipped as-is by best-zip.
> fix(package): fix the archiving of individual files

- README.md
- src/pack.ts
- src/packagers/index.ts
- src/packagers/pnpm.ts
Add support for pnpm, the third package manager after npm and yarn.
Hello from pnpm | pnpm
https://pnpm.io/
> feat(packager): add support for pnpm

- README.md
Add link to serverless-analyze-bundle-plugin, as discussed in #219
> Add external tools documentation

- src/pack.ts
- src/tests/pack.test.ts
fixes #195
also tested on real project where we have patterns on individual lambda functions and it works fine
> fix: filtering in pack.ts

- src/pre-local.ts
- src/tests/pre-local.test.ts
> fix(pre-local): correct local invoke for non node functions

- src/helper.ts
Revert #251
This will need more logic as the version mapping logic in `yarn` is completely different. While this packaging logic is still very flawed, it will work in more situations than the current master with `yarn` packaging.
due to https://github.com/floydspace/serverless-esbuild/issues/265
Will take more than a couple days to iron this out.
> fix: revert v1.23.4 dependency tree changes

- .github/workflows/pull.yml
- .github/workflows/release.yml
- README.md
- package-lock.json
- package.json
- src/helper.ts
- src/index.ts
- src/pack-externals.ts
- src/pack.ts
- src/pre-local.ts
- src/pre-offline.ts
- src/tests/helper.test.ts
- src/tests/index.test.ts
- src/tests/pack.test.ts
- src/tests/packagers/npm.test.ts
- src/tests/util.test.ts
- src/types.ts
- src/utils.ts
- tsconfig.json
Just avoiding the double release. Using "Merge Pull Request" to bring in changelog
> chore: release new version

- README.md
- src/index.ts
- src/types.ts
Resolves #285
- Allows the customisation of the output folders for the plugin
> feat: allow customisation of output folders

- src/bundle.ts
Forgot to remove these before bundle.
> fix: remove config from esbuild options

- src/pack.ts
Followup to my comment on #375 
By explicitly looking at the build dir and factoring out exclude patterns from the function level, we can better handle individual packaging of functions, especially when other build tooling is in play.
> feat: handle exclude patterns for functions

- src/pack.ts
Here's a simple proof-of-concept PR which calls `zip` with pMap and a concurrency setting of 4. The previous behaviour was to zip all functions in parallel.
The background is described here: https://github.com/floydspace/serverless-esbuild/issues/448
Three potential improvements to this PR:
- If this is a fruitful path to go down, we will want to parametrise `concurrency`. We could use `buildOptions.concurrency` which is currently used to instruct esbuild's concurrency, but perhaps having its own "zip concurrency" option is better.
- The implementation can also be cleaned up. I have simply wrapped the zip logic in an inline function ("`zipper`") but this could be refactored somewhat nicer. There are references to variables defined in the outside scope which is perhaps okay but not ideal. …
> feat: zip concurrently with pMap

- src/bundle.ts
for reference https://github.com/floydspace/serverless-esbuild/pull/491
> fix: bug in releas 1.48

- src/bundle.ts
> fix: incorrect position of optional chaining operator

- README.md
I made a simple formatting correction in the README :)
> fix: add space in README
